services:

  side-shopy-db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - side_shopy_data:/var/lib/postgresql/data
    ports:
      - 5434:5432

  side-shopy-test-db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_TEST_USERNAME}
      POSTGRES_DB: ${DATABASE_TEST_NAME}
      POSTGRES_PASSWORD: ${DATABASE_TEST_PASSWORD}
    volumes:
      - side_shopy_test_data:/var/lib/postgresql/data
    ports:
      - 5435:5432

volumes:
  side_shopy_data:
  side_shopy_test_data: